
-- ==============================================================================
-- 1. SETUP & UTILS
-- ==============================================================================

-- Note: We do not alter auth.users directly here to avoid permission issues.
-- RLS on auth.users is typically enabled by default in Supabase.

-- ==============================================================================
-- 2. PROFILES TABLE
-- Stores user stats, coins, and inventory
-- ==============================================================================

create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  username text,
  email text,
  avatar_url text,
  coins integer default 100,
  high_score integer default 0,
  inventory jsonb default '{"themes": ["default"]}'::jsonb,
  stats jsonb default '{}'::jsonb,
  claimed_achievements text[] default array[]::text[],
  last_daily_reward_claim text,
  daily_streak integer default 0,
  daily_missions jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Enable RLS
alter table public.profiles enable row level security;

-- --- PROFILES POLICIES ---
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
drop policy if exists "Users can insert their own profile." on public.profiles;
drop policy if exists "Users can update their own profile." on public.profiles;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update their own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- ==============================================================================
-- 3. CHALLENGE MATCHES TABLE
-- Handles friendly and ranked rooms
-- ==============================================================================

create table if not exists public.challenge_matches (
  id bigint generated by default as identity primary key,
  room_code text not null,
  stake_points integer default 0,
  status text default 'waiting', -- 'waiting', 'starting', 'in_progress', 'completed'
  match_type text default 'friend',
  player1_name text,
  player1_email text,
  player1_id uuid references auth.users,
  player2_name text,
  player2_email text,
  player2_id uuid references auth.users,
  is_player2_ai boolean default false,
  
  -- REALTIME SCORE COLUMNS
  player1_score integer default 0,
  player2_score integer default 0,
  winner_id uuid references auth.users,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add columns if they don't exist (Idempotency for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'challenge_matches' and column_name = 'player1_score') then
    alter table public.challenge_matches add column player1_score integer default 0;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'challenge_matches' and column_name = 'player2_score') then
    alter table public.challenge_matches add column player2_score integer default 0;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'challenge_matches' and column_name = 'winner_id') then
    alter table public.challenge_matches add column winner_id uuid references auth.users;
  end if;
end $$;

-- Enable RLS
alter table public.challenge_matches enable row level security;

-- --- MATCHES POLICIES ---
drop policy if exists "Anyone can read matches" on public.challenge_matches;
drop policy if exists "Authenticated users can create matches" on public.challenge_matches;
drop policy if exists "Players can update matches" on public.challenge_matches;

-- 1. Select: Everyone can see matches (needed for joining)
create policy "Anyone can read matches"
  on public.challenge_matches for select
  using ( true );

-- 2. Insert: Only logged in users can create rooms
create policy "Authenticated users can create matches"
  on public.challenge_matches for insert
  with check ( auth.role() = 'authenticated' );

-- 3. Update: Players involved can update scores/status
create policy "Players can update matches"
  on public.challenge_matches for update
  using ( 
    auth.uid() = player1_id 
    OR auth.uid() = player2_id 
    OR player2_id IS NULL 
  );

-- ==============================================================================
-- 4. ENABLE REALTIME
-- ==============================================================================

begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;

alter publication supabase_realtime add table public.challenge_matches;
